name: Demo to create automatic PR

on:
  push:
    branches:
      - feature
      - develop
      - main
      
jobs:
  AutomaticPR:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4
      - run: |
          git config user.email noreply@github.com
          git config user.name "GitHub actions"
          git checkout -b feature/${{ github.sha }}
          echo date > current-date.txt
          git add current-date.txt
          git commit --message "Changes made"
          git push origin -f feature/${{ github.sha }}
          git branch -d feature/${{ github.sha }}
          
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR 1
        id: test-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "firstbranch"
          #base: develop
          title: "demo for auto pr1"
          #committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          #author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          assignees: accenturetesting19
          reviewers: accenturetesting19
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
      - name: Pull request number
        run: |
          echo "Pull Request Number - ${{ steps.test-1.outputs.pull-request-number }}"

      - name: Approve Pull Request1
        #uses: juliangruber/approve-pull-request-action@v1
        run: |
           echo "approver name - ${{ secrets.APPROVER_DEMO }}"
        #with:
         #github-token: ${{ secrets.APPROVER_DEMO }}
         #number: ${{ steps.test-1.outputs.pull-request-number }}
