name: Demo to create automaticPR
on:
  push:
    branches:
      - main
jobs:
  PRcreation:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
        
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
        
      - name: Update author information
        run: echo ${{env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
        
      - name: Raise PR
        id: first
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "dev"
          base: main
          title: "demo for auto pr"
          committer: ${{env.GIT_COMMIT_AUTHOR_NAME }} <${{env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{env.GIT_COMMIT_AUTHOR_NAME }} <${{env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{secrets.GITHUB_TOKEN }}
          delete-branch: true

      - name: Pull request number
        run: |
          echo "Pull Request Number - ${{ steps.first.outputs.pull-request-number }}"

      - name: Approve pull Request
        if: ${{ steps.first.outputs.pull-request-number }}
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #github-token: ${{ secrets.APPROVER_DEMO }}
          pull-request-number: ${{ steps.first.outputs.pull-request-number }}
     # - name: Approve Pull Request1
      #  uses: juliangruber/approve-pull-request-action@v1
       # with:
        #  github-token: ${{ secrets.APPROVER_DEMO }}
         # #number: ${{ steps.test1.outputs.pull-request-number }}

      - name: Merge Pull request1
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.first.outputs.pull-request-number }}
        #method: squash
