name: demo to create PR

on:
  push:
    branches:
      - develop
      #- main
    
jobs:
  AutomaticPR:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR 1
        id: test-1
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "Autoprcreate"
          #base: main
          title: "Automatic Pull request creation"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
            - Updated with *today's* date
          labels: automerge
          assignees: accenturetesting19
          reviewers: accenturetesting19
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull request number
        run: |
          echo "Pull Request Number - ${{ steps.test-1.outputs.pull-request-number }}"

